app:
  name: "MyChatApp"
  deployment: "production"

  fetchers:
    RestAPIFetcher:
      processor: flatten_user_dict
      params:
        base_url: "https://jsonplaceholder.typicode.com"
        token: ""

    AzureSearchFetcher:
      processor: noop
      params:
        query: ""                       
        filter: ""                      
        top_k: 5
        skip: 0
        include_total_count: true
        facets:
          - "type,count:5"             # show top types (paragraph, table, vector‑drawing)
        highlight_fields:
          - "text"
        search_fields:
          - "text"                      # only search on our text field
        select_fields:
          - "id"
          - "page_number"
          - "chunk_index"
          - "type"
          - "text"
          - "image_path"
          - "source_pdf"
          - "width"
          - "height"
          - "area"
          - "procedureTitle"           # include the new procedure title field
        semantic: true                 # use semantic ranking
        semantic_config: "default-semantic"
        vector_search: true
        vector_field: "contentVector"
  llm:
    type: azure_openai
    processor: default              # optional
    deployment: gpt-4.1-mini
    model_name: gpt-4.1-mini
    endpoint: https://embeddingmodelrecoveredspaces.openai.azure.com/
    api_type: Azure
    api_version: 2024-12-01-preview
    api_base_url: https://nunot-masez9tz-eastus2.cognitiveservices.azure.com/

    prompts:
      folder:   recovered_space
      system:   system_prompt.j2
      defaults:
        - chat_prompt.j2             # you can list more files here
        # - another_prompt.j2

    params:
      max_tokens:              200
      temperature:             0.2
      top_p:                   0.9
      frequency_penalty:       0.0
      presence_penalty:        0.0
      stop:                    ["<|im_end|>"]
      repetition_penalty:      1.0
      n:                        1
      stream:                  false
      logit_bias:              null


  ai_search:
    endpoint: "https://ragtests.search.windows.net"
    api_key: ""           # <- pulled from Key Vault at runtime

    index:
      name:            "pdf_index_1"
      skillset_name:   "chat-skillset"
      indexer_name:    "chat-indexer"
      indexes_path:    "resources/AI_search_indexes"
      index_yml_path:  "pdf_index.yml"

      vector_dim:       1536
      vector_field:     "contentVector"
      index_text_field: "text"

      semantic_content_fields:
        - "text"
        - "source_pdf"
      semantic_title_field: "text" 

      embedding:
        url:          "https://nunot-masez9tz-eastus2.cognitiveservices.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-05-15"
        vectorizer_base_url: "https://embeddingmodelrecoveredspaces.openai.azure.com/"
        deployment:   "text-embedding-ada-002"
        model_name:   "text-embedding-ada-002"
        api_version:  "2023-05-15"
        api_key: ""       # <- also filled from Key Vault

  form_recognizer:
    endpoint:      "https://pdf-analyser.cognitiveservices.azure.com/"
    api_version:   "2023-02-28-preview"
    model_id:      "prebuilt-document"
    pages_per_call: 100
    api_key:       ""   # will be filled from Key Vault

  secrets_mapping:
    AzureSearchAPIKey:      ["ai_search", "api_key"]
    AzureSearchEmbeddingAPIKey: ["ai_search", "index", "embedding", "api_key"]
    OpenAIAPIKey:           ["llm", "api_key"]
    FormRecognizerAPIKey:         ['form_recognizer','api_key']
  
  # Storage configuration for various Azure Storage services
  storage:
    # Global storage account settings (optional, if using single account)
    default_account_name: "mystorageaccount"
    default_resource_group: "myresourcegroup"
    default_subscription_id: "your-subscription-id"
    
    # Blob Storage configuration
    blob_storage:
      account_name: "mystorageaccount"
      container_name: "documents"
      use_managed_identity: true  # Recommended for production
      endpoint_suffix: "core.windows.net"  # Use "core.chinacloudapi.cn" for Azure China
      # account_key and connection_string will be injected from Key Vault

    file_mappings:
      base_container: "conversionfiles"
      type_mappings:
        # PDF documents go to pdf/raw directory
        ".pdf": "pdf/raw"
        ".PDF": "pdf/raw"
        
        # Text files go to transcripts/raw
        ".txt": "transcripts/raw"
        ".TXT": "transcripts/raw"
        
        # Audio files
        ".mp3": "audio/raw"
        ".wav": "audio/raw"
        ".m4a": "audio/raw"
        
        # Video files
        ".mp4": "video/raw"
        ".avi": "video/raw"
        ".mov": "video/raw"
        
        # Document formats
        ".docx": "documents/word"
        ".doc": "documents/word"
        ".pptx": "documents/powerpoint"
        ".ppt": "documents/powerpoint"
        ".xlsx": "documents/excel"
        ".xls": "documents/excel"
        
        # Images
        ".jpg": "images/raw"
        ".jpeg": "images/raw"
        ".png": "images/raw"
        ".gif": "images/raw"
        ".bmp": "images/raw"
        
        # Archive files
        ".zip": "archives/compressed"
        ".rar": "archives/compressed"
        ".7z": "archives/compressed"
        
        # JSON and XML data
        ".json": "data/structured"
        ".xml": "data/structured"
        ".csv": "data/tabular"
        
        # Code files
        ".py": "code/python"
        ".js": "code/javascript"
        ".html": "code/web"
        ".css": "code/web"
        
        # Default fallback for unknown types
        "default": "misc/other"
    
    # File Share configuration  
    file_share:
      account_name: "mystorageaccount"
      share_name: "shared-files"
      directory_path: "uploads"  # Optional subdirectory
      use_managed_identity: true
      endpoint_suffix: "core.windows.net"
    
    # Table Storage configuration (for metadata, logs, etc.)
    table_storage:
      account_name: "mystorageaccount"
      table_name: "DocumentMetadata"
      use_managed_identity: true
      endpoint_suffix: "core.windows.net"
    
    # Queue Storage configuration (for async processing)
    queue_storage:
      account_name: "mystorageaccount"
      queue_name: "document-processing"
      use_managed_identity: true
      endpoint_suffix: "core.windows.net"

  other:
    debug: true
    log_level: INFO


# If semantic fields are not specified, the following defaults will be used:
# semantic_content_fields: ["text"]
# semantic_title_field: "questionoranswer"

# Path Guidelines:
# ✅ Good: "resources/configs/file.yml"
# ❌ Avoid: "resources\\configs\\file.yml" (may cause issues on non-Windows systems)
