app:
  name: "MyChatApp"
  deployment: "production"

  fetchers:
    RestAPIFetcher:
      processor: flatten_user_dict
      params:
        base_url: "https://jsonplaceholder.typicode.com"
        token: ""

    AzureSearchFetcher:
      processor: noop
      params:
        # required
        query: ""                       # e.g. will be filled from your orchestrator build_args
        filter: ""                      # e.g. "speaker eq 'David'"
        # optional with defaults
        top_k: 5
        skip: 0
        include_total_count: true
        facets:
          - "speaker,count:5"
          - "topic"
        highlight_fields:
          - "text"
        search_fields: null             # or omit entirely if you want server defaults
        select_fields:
          - "id"
          - "filename"
          - "block_id"
          - "chunk_index"
          - "part"
          - "speaker"
          - "timestamp"
          - "tokens"
          - "video_url"
          - "keyword"
          - "topic"
          - "text"
        semantic: false
        semantic_config: null
        vector_search: true
        hybrid: null
        vector_field: "contentVector"

  llm:
    type: azure_openai
    processor: default              # optional
    deployment: gpt-4.1-mini
    model_name: gpt-4.1-mini
    endpoint: https://embeddingmodelrecoveredspaces.openai.azure.com/
    api_type: Azure
    api_version: 2024-12-01-preview
    api_base_url: https://nunot-masez9tz-eastus2.cognitiveservices.azure.com/

    prompts:
      folder:   recovered_space
      system:   system_prompt.j2
      defaults:
        - chat_prompt.j2             # you can list more files here
        # - another_prompt.j2

    params:
      max_tokens:              200
      temperature:             0.2
      top_p:                   0.9
      frequency_penalty:       0.0
      presence_penalty:        0.0
      stop:                    ["<|im_end|>"]
      repetition_penalty:      1.0
      n:                        1
      stream:                  false
      logit_bias:              null


  ai_search:
    endpoint: "https://ragtests.search.windows.net"
    api_key: ""           # <- pulled from Key Vault at runtime

    index:
      name:            "test_transcript"
      skillset_name:   "chat-skillset"
      indexer_name:    "chat-indexer"
      indexes_path:    "resources/AI_search_indexes"
      index_yml_path:  "transcripts.yml"

      vector_dim:       1536
      vector_field:     "contentVector"
      index_text_field: "text"

      embedding:
        url:          "https://nunot-masez9tz-eastus2.cognitiveservices.azure.com/openai/deployments/text-embedding-ada-002/embeddings?api-version=2023-05-15"
        deployment:   "text-embedding-ada-002"
        model_name:   "text-embedding-ada-002"
        api_version:  "2023-05-15"
        api_key: ""       # <- also filled from Key Vault

  secrets_mapping:
    AzureSearchAPIKey:      ["ai_search", "api_key"]
    AzureSearchEmbeddingAPIKey: ["ai_search", "index", "embedding", "api_key"]
    OpenAIAPIKey:           ["llm", "api_key"]

  other:
    debug: true
    log_level: INFO
